/**
 * DraftCard — preview of a single draft case study on /admin/draft-cases.
 *
 * Inv-PB-5 (resists shallow PRs): the card shows the full scenario text
 * plus the optional practitioner note so the reviewer can read the
 * full intent before approving.
 */
import type { DraftRecord } from './DraftStore.ts';

interface Props {
  draft: DraftRecord;
  onApprove: (id: string) => void;
  onReject: (id: string) => void;
}

export function DraftCard({ draft, onApprove, onReject }: Props) {
  return (
    <article
      data-testid={`pybe-draft-card-${draft.id}`}
      className="pybe-card"
    >
      <header className="mb-3 flex flex-wrap items-center gap-2">
        <span className="rounded-full bg-amber-100 px-2 py-0.5 font-mono text-xs text-amber-800">
          {draft.id}
        </span>
        <span className="rounded-full bg-stone-100 px-2 py-0.5 text-xs text-stone-700">
          level {draft.level}
        </span>
        <span className="rounded-full bg-stone-100 px-2 py-0.5 text-xs text-stone-700">
          {draft.jonassenType}
        </span>
        <span className="ml-auto text-xs text-stone-400">
          generated by <code>{draft.generatedBy}</code>
        </span>
      </header>

      <h3 className="mb-2 text-lg font-semibold text-stone-900">{draft.title}</h3>

      <details open className="mb-3">
        <summary className="cursor-pointer text-sm font-medium text-stone-600">
          Scenario
        </summary>
        <p className="mt-2 whitespace-pre-line text-sm text-stone-700">
          {draft.scenario}
        </p>
      </details>

      {draft.practitionerNote && (
        <details className="mb-3">
          <summary className="cursor-pointer text-sm font-medium text-stone-600">
            Practitioner note (in the wild)
          </summary>
          <p className="mt-2 text-sm text-stone-700">{draft.practitionerNote}</p>
        </details>
      )}

      <div className="mb-3 flex flex-wrap gap-1">
        {draft.constructHint.map((c) => (
          <span
            key={c}
            className="rounded-full bg-emerald-100 px-2 py-0.5 font-mono text-xs text-emerald-800"
          >
            {c}
          </span>
        ))}
      </div>

      <div className="flex items-center justify-end gap-2">
        <button
          data-testid={`pybe-draft-reject-${draft.id}`}
          type="button"
          onClick={() => onReject(draft.id)}
          className="pybe-btn-ghost text-xs text-rose-700"
        >
          Reject
        </button>
        <button
          data-testid={`pybe-draft-approve-${draft.id}`}
          type="button"
          onClick={() => onApprove(draft.id)}
          className="pybe-btn-primary text-xs"
        >
          Approve &amp; publish
        </button>
      </div>
    </article>
  );
}