/**
 * Generates docs/InvariantTests.md from the registry in tests/invariants/_map.ts.
 * Phase-8 acceptance: docs/InvariantTests.md is regenerated and committed.
 *
 * Usage: tsx scripts/generate-invariant-docs.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const MAP_PATH = resolve(__dirname, '..', 'tests', 'invariants', '_map.ts');
const DOCS_PATH = resolve(__dirname, '..', 'docs', 'InvariantTests.md');

async function main(): Promise<void> {
  const mod = (await import(MAP_PATH)) as { INVARIANTS: InvariantEntry[] };
  const all = mod.INVARIANTS;

  const grouped: Record<string, typeof all> = {
    pedagogical: [],
    architectural: [],
    interface: [],
    data: [],
  };
  for (const inv of all) {
    grouped[inv.category]!.push(inv);
  }

  let md = '# Invariant Tests\n\n';
  md += '> Auto-generated by `scripts/generate-invariant-docs.ts`.\n';
  md += `> Source of truth: \`tests/invariants/_map.ts\`.\n`;
  md += `> Generated at build time — do not hand-edit.\n\n`;
  md += `**Total invariants: ${all.length}**\n\n`;

  md += '## Coverage by category\n\n';
  md += '| Category | Invariants |\n|---|---|\n';
  for (const cat of ['pedagogical', 'architectural', 'interface', 'data']) {
    md += `| ${cat} | ${grouped[cat]!.length} |\n`;
  }
  md += '\n';

  for (const cat of ['pedagogical', 'architectural', 'interface', 'data']) {
    md += `## ${capitalize(cat)}\n\n`;
    md += '| Code | Phase | Description | Tests |\n';
    md += '|---|---|---|---|\n';
    for (const inv of grouped[cat]!) {
      md += `| \`${inv.code}\` | ${inv.phase} | ${inv.description} | ${inv.tests.map((t) => '`' + t + '`').join(', ')} |\n`;
    }
    md += '\n';
  }

  md += '## How to add a new invariant\n\n';
  md += '1. Add the entry to `tests/invariants/_map.ts`.\n';
  md += '2. Write the test in the matching `tests/invariants/<category>.test.ts(x)` file.\n';
  md += '3. Re-run `npm run generate-invariant-docs` to refresh this file.\n';
  md += '4. The `tests/invariants/data.test.ts` meta-tests assert the registry stays in sync.\n\n';
  md += '## How to fail CI\n\n';
  md += '- **Remove any invariant test** → meta-test "every test name literally appears" fails.\n';
  md += '- **Remove the registry entry** → meta-test "every invariant has at least one test" fails.\n';
  md += '- **Introduce a score cap** (e.g. `Math.min(score, 9999)`) in `ScoringEngine.ts` → `INV-PB-3` test fails.\n';
  md += '- **Add a hardcoded metaphor ID list** → `INV-A2` test fails.\n';

  mkdirSync(dirname(DOCS_PATH), { recursive: true });
  writeFileSync(DOCS_PATH, md, 'utf-8');
  console.log(`[pybe] wrote ${DOCS_PATH} (${all.length} invariants across 4 categories)`);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

interface InvariantEntry {
  code: string;
  category: string;
  phase: number;
  description: string;
  tests: string[];
}

main().catch((err) => {
  console.error('[pybe] fatal:', err);
  process.exit(1);
});