import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {values,getValue,evaluate,questions} from './semantics';
import './styles.css';
import Icon from './Icon';
import GuidedPractice from './GuidedPractice';
const chapters=['Welcome','The gate','Something','Python','The runner','OR','The VIP tent','AND','Try it','Quiz','Reflect'];
const KEY='pybe-mela-reflection-v1';
function readSaved(){try {const s=JSON.parse(localStorage.getItem(KEY));return s&&typeof s.text==='string'&&typeof s.savedAt==='string'?s:null;}catch{return null}}
const Code=({children})=><pre><code>{children}</code></pre>;
function Note({children}){return <div className="note"><span>✦</span><div>{children}</div></div>}
function Heading({tag,title,children}){return <><p className="eyebrow">{tag}</p><h1>{title}</h1>{children&&<p className="lead">{children}</p>}</>}
function Fair({vip=false}){return <div className={'fair '+(vip?'vip':'')} role="img" aria-label={vip?'A village fair with a VIP tent, ticket and wristband':'A village fair at sunset with a gate, stalls, lights and a Ferris wheel'}><div className="sun"/><div className="stars">✦ · &nbsp; ✧ &nbsp; · ✦</div><div className="bunting">▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼</div><div className="wheel"><i/><i/><i/><i/><b>✧</b></div><div className="stall s1"><span><Icon kind="🍬"/></span></div><div className="stall s2"><span><Icon kind="🪔"/></span></div><div className="gate"><b>{vip?'VIP TENT':'VILLAGE MELA'}</b><div>{vip?<><Icon kind="🎟️"/> + <Icon kind="🎗️"/></>:'WELCOME'}</div></div><div className="path"/><div className="visitor"><Icon kind="🚶"/></div><div className="fairCaption">{vip?'Two checks. One decision.':'An evening at the village mela'}</div></div>}
function Basket({truthy=false}){const items=values.filter(v=>truthy?['sweet','name','coin','textzero','listzero','negative'].includes(v.id):['empty','blank','zero','none','false'].includes(v.id));const [chosen,setChosen]=useState(items[0].id);const v=getValue(chosen);return <><div className="valueGrid">{items.map(x=><button key={x.id} className={'valueCard '+(x.id===chosen?'selected':'')} onClick={()=>setChosen(x.id)} aria-pressed={x.id===chosen}><span><Icon kind={x.icon}/></span><code>{x.code}</code><small>{x.name}</small></button>)}</div><div className="verdict" key={chosen}><span><Icon kind={v.icon}/></span><div><code>{v.code}</code><p>{truthy?'Something is here → truthy':'Empty, zero, absent, or False → falsy'}</p></div><b className={truthy?'green':'amber'}>{truthy?'Truthy':'Falsy'}</b></div></>}
function Runner({operator='or',sandbox=false}){
 const [leftId,setLeft]=useState(operator==='or'?'blank':'none');const [rightId,setRight]=useState(operator==='or'?'guest':'band');const [op,setOp]=useState(operator);const [phase,setPhase]=useState(0);const timers=useRef([]);
 const left=getValue(leftId),right=getValue(rightId),result=evaluate(left,op,right);
 function cancel(){timers.current.forEach(clearTimeout);timers.current=[];}
 useEffect(()=>()=>cancel(),[]);
 function change(set,value){cancel();setPhase(0);set(value)}
 function run(){cancel();setPhase(1);const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;timers.current=[setTimeout(()=>setPhase(2),reduced?0:750),setTimeout(()=>setPhase(3),reduced?0:1550)]}
 return <div className="runner"><div className="controls"><label>{sandbox?'First value':op==='or'?'Customer name':'Ticket'}<select value={leftId} onChange={e=>change(setLeft,e.target.value)}>{(sandbox?values:values.filter(v=>(op==='or'?['blank','name','zero']:['none','ticket','zero']).includes(v.id))).map(v=><option key={v.id} value={v.id}>{v.code}</option>)}</select></label>{sandbox?<label>Operator<select value={op} onChange={e=>change(setOp,e.target.value)}><option>or</option><option>and</option></select></label>:<strong className="operator">{op}</strong>}<label>{sandbox?'Second value':op==='or'?'Fallback':'Wristband'}<select value={rightId} onChange={e=>change(setRight,e.target.value)}>{(sandbox?values:values.filter(v=>(op==='or'?['guest','blank','zero']:['band','blank','none']).includes(v.id))).map(v=><option key={v.id} value={v.id}>{v.code}</option>)}</select></label></div>
 <div className="route"><div className={'stop '+(phase>=1?'lit':'')}><small>01 · FIRST VALUE</small><span><Icon kind={left.icon}/></span><code>{left.code}</code><p>{phase>=1?(left.truth?'Truthy':'Falsy'):'Ready to check'}</p></div><div className={'bridge '+(phase>=2&&result.rightEvaluated?'travel':'')}><span>➜</span></div><div className={'stop '+(phase>=2?(result.rightEvaluated?'lit':'skipped'):'')}><small>02 · SECOND VALUE</small><span><Icon kind={right.icon}/></span><code>{right.code}</code><p>{phase>=2?(result.rightEvaluated?'Evaluated':'SKIPPED'):'Not checked yet'}</p></div><div className="bridge">➜</div><div className={'stop result '+(phase===3?'lit':'')}><small>03 · RETURNED VALUE</small><span><Icon kind="📦"/></span><code>{phase===3?result.value.code:'?'}</code><p>{phase===3?`Type: ${result.value.type}`:'The actual value'}</p></div></div>
 <Code>{`${left.code} ${op} ${right.code}${phase===3?'  # returns '+result.value.code:''}`}</Code><button className="primary" onClick={run}>{phase?'↻ Replay':'▶ Follow the checks'}</button><p className="trace" role="status">{phase===0?'Choose values, then follow the checks.':phase===1?`First: ${left.code} is ${left.truth?'truthy':'falsy'}.`:phase===2?result.rightEvaluated?'The rule needs the second value. Evaluate it now.':'Stop early. The second value is not evaluated.':`Returned ${result.value.code}, not converted to True or False.`}</p></div>
}
function Bell(){const [ticket,setTicket]=useState(false);const [ran,setRan]=useState(false);return <div className="bell"><label className="toggle"><input type="checkbox" checked={ticket} onChange={e=>{setTicket(e.target.checked);setRan(false)}}/> Give the visitor a ticket</label><Code>{`ticket = ${ticket?'"Ticket"':'None'}\n\ndef ring_bell():\n    print("Ding!")\n    return "VIP"\n\nresult = ticket and ring_bell()`}</Code><button onClick={()=>setRan(true)}>▶ Check the entrance</button><div className="bellResult" role="status">{ran?<><span className={ticket?'ring':''}><Icon kind={ticket?'🔔':'🔕'}/></span><b>{ticket?'Ding! Result: "VIP"':'Bell skipped. Result: None'}</b></>:<><span><Icon kind="🔔"/></span><b>Will the bell ring?</b></>}</div><small>Visual simulation; no sound plays.</small></div>}
function Quiz({answers,setAnswers}){const done=questions.every((_,i)=>answers[i]!==undefined);const score=questions.filter((q,i)=>answers[i]===q.correct).length;return <><div className="quiz">{questions.map((q,i)=><fieldset key={q.q}><legend><span>0{i+1}</span> {q.q}</legend><div className="options">{q.options.map((o,j)=><button key={o} className={answers[i]===j?'selected':''} onClick={()=>setAnswers(a=>({...a,[i]:j}))} aria-pressed={answers[i]===j}>{o}</button>)}</div>{answers[i]!==undefined&&<p className={'feedback '+(answers[i]===q.correct?'green':'amber')} role="status">{answers[i]===q.correct?'✓ Correct. ':'↻ Try again. '}{q.why}</p>}</fieldset>)}</div><Note>{done?`${score}/3 correct. ${score===3?'Well done! You understand the checks and the returned values.':'Read the explanations and try another answer.'}`:'Three small checks. Choose an answer to see why it works.'}</Note></>}
function Reflection({answers}){const [saved,setSaved]=useState(readSaved);const [text,setText]=useState(()=>readSaved()?.text||'');const [error,setError]=useState('');const same=saved?.text===text;function submit(e){e.preventDefault();const clean=text.trim();if(!clean){setError('Write a short explanation before submitting.');return}const data={text:clean,savedAt:new Date().toISOString(),quizAnswers:answers,quizScore:questions.filter((q,i)=>answers[i]===q.correct).length};try{localStorage.setItem(KEY,JSON.stringify(data));setSaved(data);setText(clean);setError('')}catch{setError('Your browser could not save this. Copy your answer before leaving, or enable local storage and try again.')}}return <><div className="summary"><div><b>Truthy / falsy</b><p>How a value behaves in a condition.</p></div><div><b>or</b><p>First truthy value, or the last value.</p></div><div><b>and</b><p>First falsy value, or the last value.</p></div></div><form onSubmit={submit}><label htmlFor="reflection">Explain in your own words</label><p>Why does <code>"" or "Guest"</code> return <code>"Guest"</code>? When can Python skip the second expression?</p><textarea id="reflection" value={text} onChange={e=>{setText(e.target.value);setError('')}} maxLength={2000} placeholder="The empty name is falsy, so…" rows={4}/><div className="formRow"><small>{text.length}/2000 · Saved only in this browser after Submit.</small><button className="primary" type="submit" disabled={!text.trim()||same}>{same?'✓ Submitted':saved?'Update submission':'Submit reflection →'}</button></div></form>{error&&<p role="alert" className="feedback amber">{error}</p>}{saved&&<div className="thanks" role="status"><span>✦</span><div><h2>{same?'Well done. You turned a story into understanding!':'You have an earlier saved reflection.'}</h2><p>{same?'Your reflection is saved. Keep experimenting—small checks make strong Python habits.':'Your edits are not saved yet. Select Update submission to keep them.'}</p><small>Last saved: {new Date(saved.savedAt).toLocaleString()}</small></div></div>}</>}
function App(){const [step,setStep]=useState(0);const [answers,setAnswers]=useState(()=>{const a=readSaved()?.quizAnswers;return a&&typeof a==='object'&&!Array.isArray(a)?a:{}});const panel=useRef(null);function go(n){setStep(n);window.scrollTo({top:0,behavior:'instant'})}useEffect(()=>{panel.current?.focus({preventScroll:true})},[step]);return <main className="app"><header><a className="brand" href="#" onClick={e=>{e.preventDefault();go(0)}}>Py<span>Be</span><small>LEARN THROUGH STORIES</small></a><div className="lessonLabel">PYTHON ESSENTIALS <b>The Mela Gatekeeper</b></div><span className="counter">{String(step+1).padStart(2,'0')} <i>/ 11</i></span></header><div className="progress" role="progressbar" aria-label="Lesson position" aria-valuemin={1} aria-valuemax={11} aria-valuenow={step+1}><i style={{width:`${(step+1)/11*100}%`}}/></div><nav aria-label="Lesson chapters">{chapters.map((c,i)=><button key={c} onClick={()=>go(i)} className={i===step?'current':''} aria-current={i===step?'step':undefined}><span>{i+1}</span>{c}</button>)}</nav>
 <section className="stage" ref={panel} tabIndex={-1} aria-label={chapters[step]}><div className="scene" key={step}>
 {step===0&&<div className="split hero"><div><p className="eyebrow">A PYTHON STORY · ABOUT 8 MINUTES</p><h1>A little mela.<br/>A clever <em>gatekeeper.</em></h1><p className="lead">At the village fair, some baskets are full. Some are empty. One simple check changes what happens next.</p><div className="chips"><span>Truthiness</span><span>Short-circuit and / or</span></div><button className="primary" onClick={()=>go(1)}>Enter the mela →</button><p className="muted">First the story. Then the Python.</p></div><Fair/></div>}
 {step===1&&<><Heading tag="01 · AT THE ENTRANCE" title="Different things. The same empty signal.">The gatekeeper asks, “Is anything here?” An empty basket, a blank slip and zero coins all signal nothing to use.</Heading><Basket/><Note>He is checking what you carry—not judging you! In Python, these values behave as false in a condition. They are called <strong>falsy</strong>.</Note></>}
 {step===2&&<><Heading tag="02 · THE NEXT VISITORS" title="Something is enough.">A sweet, a name or a nonzero number gives the gatekeeper something to work with. Tap each visitor’s item.</Heading><Basket truthy/><Note><code>"0"</code> has a character. <code>[0]</code> has an item. Both are nonempty, so both are truthy—even though they contain a zero.</Note></>}
 {step===3&&<><Heading tag="03 · STORY → PYTHON" title="Python asks the same question.">An if statement tests truthiness. You do not need to compare a list with True.</Heading><div className="split"><div><Code>{`basket = ["laddu"]\n\nif basket:\n    print("Something to share!")\nelse:\n    print("The basket is empty.")`}</Code><Note><code>bool(value)</code> gives you an actual <code>True</code> or <code>False</code>. The original value stays the same.</Note></div><div className="paper"><h2>A quick translation</h2><div><code>bool([])</code><b className="amber">False</b></div><div><code>bool([0])</code><b className="green">True</b></div><div><code>bool("")</code><b className="amber">False</b></div><div><code>bool("0")</code><b className="green">True</b></div><p>Falsy is a behavior in a condition. <code>None</code>, <code>[]</code> and <code>""</code> are different values, not the Boolean <code>False</code>.</p></div></div><p className="muted">Empty tuples, dictionaries and sets are falsy too. The basket analogy covers these built-in examples; custom objects can define their own truth behavior.</p></>}
 {step===4&&<div className="split"><div><Heading tag="04 · THE SHOPKEEPER’S RUNNER" title="Take the first useful offer.">“Ask the customer first. If they give you something, bring it back. Otherwise, ask the guarantor.”</Heading><div className="storySteps"><p><b>1</b> The customer offers something? Stop here.</p><p><b>2</b> Empty-handed? Visit the guarantor.</p><p><b>3</b> Bring back the actual payment.</p></div><Note>This is <code>or</code>. If neither offers anything useful, the runner still returns the second value—even if it is empty.</Note></div><div className="storyArt"><div className="bunting">▼ ▼ ▼ ▼ ▼ ▼ ▼</div><span className="runnerIcon"><Icon kind="🏃"/></span><h2>Customer <em>or</em> guarantor</h2><div className="offer"><span><Icon kind="🤲"/><small>Ask first</small></span><b>→</b><span><Icon kind="💰"/><small>Only if needed</small></span></div><p>The parcel comes back.<br/>Not a yes/no report.</p></div></div>}
 {step===5&&<><Heading tag="05 · WATCH OR WORK" title="An empty name? Use “Guest”.">or returns the first value if it is truthy. Otherwise, it evaluates and returns the second value.</Heading><Runner/><Note>Try <code>"Asha" or "Guest"</code>: the fallback is skipped. Then try <code>"" or 0</code>: the result is <code>0</code>. The result does not have to be truthy.</Note></>}
 {step===6&&<div className="split"><div><Heading tag="06 · THE VIP TENT" title="No ticket? Stop the checks.">The VIP tent needs a ticket and a wristband. If the ticket is missing, the gatekeeper does not bother checking the wristband.</Heading><div className="storySteps"><p><b>1</b> Missing ticket → stop immediately.</p><p><b>2</b> Ticket present → check the wristband.</p><p><b>3</b> Both truthy → the condition passes.</p></div><Note>This is <code>and</code>. It returns the first value if falsy; otherwise, it evaluates and returns the second value.</Note></div><Fair vip/></div>}
 {step===7&&<><Heading tag="07 · SHORT-CIRCUIT AND" title="A skipped check does no work.">The bell function represents the second check. Without a ticket, Python never calls it.</Heading><div className="split"><Bell/><div className="paper"><h2>Why “short-circuit”?</h2><p>Once the first value determines what to do, Python skips the second expression.</p><Code>{`None and ring_bell()\n# returns None; no call\n\n"Ticket" and ring_bell()\n# calls the function\n# returns "VIP"`}</Code><Note><code>and</code> also returns a value, not necessarily a Boolean. If both values are truthy, it returns the second one.</Note></div></div></>}
 {step===8&&<GuidedPractice><Runner sandbox/></GuidedPractice>}
 {step===9&&<><Heading tag="09 · A SMALL KNOWLEDGE CHECK" title="What did the gatekeeper teach you?">Three questions. No timer. You can change an answer after reading the feedback.</Heading><Quiz answers={answers} setAnswers={setAnswers}/></>}
 {step===10&&<><Heading tag="10 · MAKE THE IDEA YOURS" title="From the mela to your own words.">A useful habit: check truthiness, follow the order, and name the actual value returned.</Heading><Reflection answers={answers}/></>}
 </div></section><footer><button disabled={step===0} onClick={()=>go(step-1)}>← Back</button><span>Story → idea → experiment</span>{step<10?<button className="primary" onClick={()=>go(step+1)}>{step===9?'Reflect →':'Continue →'}</button>:<button onClick={()=>go(0)}>Revisit the story ↺</button>}</footer><p className="footnote">PyBe · Scenario-first Python · No account needed</p></main>}
createRoot(document.getElementById('root')).render(<App/>);
