const { resetData } = require('./data/store');
require('dotenv').config();

const scenarios = [
  // ─── ORIGINAL BEGINNER SCENARIOS ────────────────────────────────────────────
  {
    title: 'Bag Weight Label',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'A student has one school bag with a weight written on a scale.',
    prompt: 'What single piece of information would you store so the computer can remember the bag weight?',
    objectives: ['Identify one value', 'Give the value a name', 'Connect naming to a variable'],
    sampleReasoning: 'I only need to remember the bag weight, so I would store it with a clear name.',
    effectivenessScore: 96,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Rainy Day Choice',
    difficulty: 'Beginner',
    concepts: ['conditionals'],
    context: 'Before leaving home, a learner checks whether it is raining.',
    prompt: 'What small decision rule would help the learner decide whether to carry an umbrella?',
    objectives: ['Notice one condition', 'Choose one action', 'Map the rule to if/else'],
    sampleReasoning: 'If it is raining, carry an umbrella. Otherwise, leave it at home.',
    effectivenessScore: 95,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Two Snack Prices',
    difficulty: 'Beginner',
    concepts: ['arithmetic', 'variables'],
    context: 'A learner buys one samosa and one juice from the canteen.',
    prompt: 'How would you figure out the total cost using just the two prices?',
    objectives: ['Store two values', 'Add values', 'Name the result'],
    sampleReasoning: 'I would keep the two prices separately and add them to get the total.',
    effectivenessScore: 94,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Greeting by Name',
    difficulty: 'Beginner',
    concepts: ['strings', 'variables'],
    context: 'A classroom screen should greet one learner by name.',
    prompt: 'What text should the computer remember, and how should it combine that text into a greeting?',
    objectives: ['Store text', 'Combine text', 'Recognize strings'],
    sampleReasoning: 'The computer should store the learner name and place it inside a greeting sentence.',
    effectivenessScore: 93,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Pass Mark Check',
    difficulty: 'Beginner',
    concepts: ['comparisons', 'conditionals'],
    context: 'A learner receives one test score and wants to know whether it is at least the pass mark.',
    prompt: 'What comparison would decide if the learner passed?',
    objectives: ['Compare two numbers', 'Create a yes/no result', 'Map comparison to condition'],
    sampleReasoning: 'I would compare the score with the pass mark and decide pass if it is high enough.',
    effectivenessScore: 92,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Pocket Money Left',
    difficulty: 'Beginner',
    concepts: ['subtraction', 'variables'],
    context: 'A learner starts with pocket money and spends a small amount on stationery.',
    prompt: 'What two values matter, and how would you find the money left?',
    objectives: ['Name starting amount', 'Name spent amount', 'Subtract to find remaining value'],
    sampleReasoning: 'Start with the original money, subtract the spent amount, and store what remains.',
    effectivenessScore: 91,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Favorite Color List',
    difficulty: 'Beginner',
    concepts: ['lists'],
    context: 'Three friends each say their favorite color.',
    prompt: 'How would you keep all three colors together instead of making separate notes?',
    objectives: ['Group related values', 'Recognize a collection', 'Map grouping to a list'],
    sampleReasoning: 'Since all values are colors, I would keep them together in one list.',
    effectivenessScore: 90,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'First Item in a Bag',
    difficulty: 'Beginner',
    concepts: ['lists', 'indexing'],
    context: 'A bag contains a pencil, eraser, and ruler in that order.',
    prompt: 'How would you ask for only the first item?',
    objectives: ['Notice order', 'Pick one position', 'Connect position to indexing'],
    sampleReasoning: 'The first item is based on its position in the ordered group.',
    effectivenessScore: 89,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Attendance Count',
    difficulty: 'Beginner',
    concepts: ['counting', 'lists'],
    context: 'A teacher has a short list of students present today.',
    prompt: 'What question would help you find how many students are present?',
    objectives: ['Recognize a group', 'Ask for its size', 'Connect size to length'],
    sampleReasoning: 'I would count how many names are in the present-students list.',
    effectivenessScore: 88,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Temperature Message',
    difficulty: 'Beginner',
    concepts: ['conditionals', 'comparisons'],
    context: 'A weather display has one temperature reading.',
    prompt: 'What simple rule would decide whether to show Hot or Comfortable?',
    objectives: ['Set a threshold', 'Compare one value', 'Choose one message'],
    sampleReasoning: 'If the temperature is above the threshold, show Hot; otherwise show Comfortable.',
    effectivenessScore: 87,
    theme: 'classic',
    caseStudyId: null
  },

  // ─── ORIGINAL EXPLORER SCENARIOS ────────────────────────────────────────────
  {
    title: 'Water Bottle Reminder',
    difficulty: 'Explorer',
    concepts: ['loops'],
    context: 'A learner wants a reminder for each break in the school day.',
    prompt: 'How would you avoid writing the same reminder separately for every break?',
    objectives: ['Recognize repeated action', 'Identify each break', 'Map repetition to a loop'],
    sampleReasoning: 'For every break, show the same water reminder.',
    effectivenessScore: 96,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Find the Longest Pencil',
    difficulty: 'Explorer',
    concepts: ['loops', 'comparisons'],
    context: 'A learner has several pencil lengths and wants to know which one is longest.',
    prompt: 'What small comparison would you repeat as you look through the lengths?',
    objectives: ['Keep current best', 'Compare one item at a time', 'Update when larger'],
    sampleReasoning: 'Start with one pencil as the longest, then compare each next pencil against it.',
    effectivenessScore: 95,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Clean Chore Checklist',
    difficulty: 'Explorer',
    concepts: ['lists', 'loops'],
    context: 'A family has a checklist of small chores for Saturday morning.',
    prompt: 'How would you go through each chore and mark it as done?',
    objectives: ['Store chores in a list', 'Process one chore at a time', 'Repeat a simple action'],
    sampleReasoning: 'Put chores in a list and handle each chore one by one.',
    effectivenessScore: 94,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Movie Age Filter',
    difficulty: 'Explorer',
    concepts: ['filtering', 'conditionals'],
    context: 'A movie app has a list of films, each with a minimum age.',
    prompt: 'What rule would decide which movies a 12-year-old can see?',
    objectives: ['Check one item rule', 'Keep allowed items', 'Map rule to filtering'],
    sampleReasoning: 'For each movie, keep it only if the learner age is at least the minimum age.',
    effectivenessScore: 93,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Classroom Supply Lookup',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'A class monitor tracks how many chalk pieces, markers, and notebooks are available.',
    prompt: 'How would you store each supply name with its count?',
    objectives: ['Pair names with values', 'Look up by name', 'Map pairs to a dictionary'],
    sampleReasoning: 'Each supply has a count, so I would store supply names as keys with counts as values.',
    effectivenessScore: 92,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Bus Stop Search',
    difficulty: 'Explorer',
    concepts: ['search', 'loops'],
    context: 'A route list contains several bus stops, and a learner wants to know if Library Stop is included.',
    prompt: 'How would you check the stops one at a time until you find the target?',
    objectives: ['Identify target', 'Scan a list', 'Stop when found'],
    sampleReasoning: 'Look at each stop and compare it with the stop I want.',
    effectivenessScore: 91,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Average Practice Score',
    difficulty: 'Explorer',
    concepts: ['averages', 'loops'],
    context: 'A learner has five practice scores and wants one average score.',
    prompt: 'What two small steps are needed before dividing?',
    objectives: ['Add all scores', 'Count scores', 'Divide total by count'],
    sampleReasoning: 'Find the total of all scores, count how many scores there are, then divide.',
    effectivenessScore: 90,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Separate Even Roll Numbers',
    difficulty: 'Explorer',
    concepts: ['modulo', 'filtering'],
    context: 'A class list has roll numbers, and the teacher wants only even-numbered students for Team A.',
    prompt: 'What small test tells you whether a roll number is even?',
    objectives: ['Test divisibility by two', 'Keep matching numbers', 'Connect remainder to modulo'],
    sampleReasoning: 'A roll number is even if dividing by two leaves no remainder.',
    effectivenessScore: 89,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Capitalize Name Tags',
    difficulty: 'Explorer',
    concepts: ['strings', 'loops'],
    context: 'A club has names typed in lowercase and wants neat name tags.',
    prompt: 'What same text-cleaning action should happen to every name?',
    objectives: ['Recognize repeated string change', 'Apply to each name', 'Create cleaned names'],
    sampleReasoning: 'For each name, convert it to title case before printing the tag.',
    effectivenessScore: 88,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Find Missing Homework',
    difficulty: 'Explorer',
    concepts: ['sets', 'comparison'],
    context: 'A teacher has one list of all students and another list of students who submitted homework.',
    prompt: 'How would you reason about who is missing from the submitted list?',
    objectives: ['Compare two groups', 'Find difference', 'Map group difference to sets'],
    sampleReasoning: 'Take everyone in the class and remove the students who submitted.',
    effectivenessScore: 87,
    theme: 'classic',
    caseStudyId: null
  },

  // ─── ORIGINAL BUILDER SCENARIOS ─────────────────────────────────────────────
  {
    title: 'Reusable Discount Rule',
    difficulty: 'Builder',
    concepts: ['functions', 'conditionals'],
    context: 'A shop gives the same discount rule to many different bills.',
    prompt: 'What inputs should a reusable discount helper receive?',
    objectives: ['Identify reusable rule', 'Choose inputs', 'Return discounted price'],
    sampleReasoning: 'The helper needs the bill amount and should return the final price after applying the rule.',
    effectivenessScore: 96,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Mini Quiz Checker',
    difficulty: 'Builder',
    concepts: ['functions', 'comparisons'],
    context: 'A quiz app needs to check one answer against one correct answer.',
    prompt: 'How would you design a tiny reusable checker for one question?',
    objectives: ['Accept learner answer', 'Accept correct answer', 'Return right or wrong'],
    sampleReasoning: 'Compare the learner answer with the correct answer and return whether they match.',
    effectivenessScore: 95,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Step Counter Function',
    difficulty: 'Builder',
    concepts: ['functions', 'lists'],
    context: 'A fitness note has a list of step counts from different walks.',
    prompt: 'How would you make a reusable helper that returns the total steps?',
    objectives: ['Accept a list', 'Add all values', 'Return total'],
    sampleReasoning: 'The function should take step counts, add them, and give back the total.',
    effectivenessScore: 94,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Safe Username Maker',
    difficulty: 'Builder',
    concepts: ['functions', 'strings'],
    context: 'A classroom app needs to turn a full name into a simple username.',
    prompt: 'What small text transformations should a username function perform?',
    objectives: ['Accept a name', 'Normalize text', 'Return username'],
    sampleReasoning: 'Make the name lowercase and remove spaces so it can be used as a username.',
    effectivenessScore: 93,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Retry Until Valid',
    difficulty: 'Builder',
    concepts: ['while loops', 'validation'],
    context: 'A form should keep asking until the learner enters a positive number.',
    prompt: 'What condition tells the program to keep asking?',
    objectives: ['Define valid input', 'Repeat while invalid', 'Stop after valid value'],
    sampleReasoning: 'Keep asking while the number is not positive, then stop once it is valid.',
    effectivenessScore: 92,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Simple Score Report',
    difficulty: 'Builder',
    concepts: ['dictionaries', 'functions'],
    context: 'A tutor wants a small report showing a learner name and score together.',
    prompt: 'How would you package two related pieces of information in one result?',
    objectives: ['Create key-value structure', 'Return structured result', 'Connect structure to dictionary'],
    sampleReasoning: 'Return a dictionary with the learner name and score as labeled values.',
    effectivenessScore: 91,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Task Status Updater',
    difficulty: 'Builder',
    concepts: ['dictionaries', 'mutation'],
    context: 'A to-do app has tasks with statuses and needs to mark one task as done.',
    prompt: 'What exact value changes when a task is completed?',
    objectives: ['Find one task', 'Change one status', 'Understand updating data'],
    sampleReasoning: 'Find the task by name and change its status from pending to done.',
    effectivenessScore: 90,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Small Receipt Builder',
    difficulty: 'Builder',
    concepts: ['functions', 'formatting'],
    context: 'A cafe wants a short text receipt for one item and its price.',
    prompt: 'What pieces should a receipt function combine into a readable line?',
    objectives: ['Accept item and price', 'Format text', 'Return one receipt line'],
    sampleReasoning: 'Combine the item name and price into one clear sentence.',
    effectivenessScore: 89,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Choose Next Scenario',
    difficulty: 'Builder',
    concepts: ['conditionals', 'adaptive logic'],
    context: 'PyBe wants to choose an easier or harder next scenario based on one score.',
    prompt: 'What simple score rule could decide the next difficulty?',
    objectives: ['Set score thresholds', 'Branch by score', 'Return next level'],
    sampleReasoning: 'If the score is high choose harder, if low choose easier, otherwise stay similar.',
    effectivenessScore: 88,
    theme: 'classic',
    caseStudyId: null
  },
  {
    title: 'Reflection Keyword Finder',
    difficulty: 'Builder',
    concepts: ['strings', 'search'],
    context: 'PyBe reads a short reflection and checks whether the learner mentioned confusion.',
    prompt: 'What tiny search would detect that the reflection may need extra support?',
    objectives: ['Choose keywords', 'Search text', 'Return support signal'],
    sampleReasoning: 'Look for words like confused or stuck and flag the reflection if they appear.',
    effectivenessScore: 87,
    theme: 'classic',
    caseStudyId: null
  },

  // ─── UADE THEME 1: THE UNDERGROUND CHAI STALL ───────────────────────────────
  {
    title: 'Ramu\'s First Chai Variable',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'Ramu runs a tiny chai stall outside IIT Ropar\'s gate. He sells only one type of chai: ginger tea at ₹15 a cup. He wants to track how many cups he sold today.',
    prompt: 'Ramu asks you: "I only need to remember one thing — how many cups I sold. What should I call it?" How would you help him store this single piece of information?',
    objectives: ['Identify one value to track', 'Give it a meaningful name', 'Understand why naming matters'],
    sampleReasoning: 'Ramu needs one piece of information — cups_sold. Naming it clearly means he can use it later to calculate earnings.',
    effectivenessScore: 95,
    theme: 'chai-stall',
    caseStudyId: 'cs-chai-stall',
    themeStep: 1,
    themeArc: 'Variables → Lists → Dicts → Functions',
    themeEmoji: '🍵'
  },
  {
    title: 'Ramu Adds More Chai Types',
    difficulty: 'Beginner',
    concepts: ['lists'],
    context: 'Ramu\'s stall became popular. Now he sells 8 types: ginger, masala, elaichi, tulsi, lemon, mint, kadak, and cutting. He has 8 separate variables: chai1, chai2... chai8. His notebook is a mess.',
    prompt: 'Ramu shouts: "I have 8 variables and if I add one more chai, I need a 9th! This is madness!" What single structure could hold ALL his chai types together?',
    objectives: ['Feel the pain of too many variables', 'Discover the concept of grouping', 'Map grouping to a Python list'],
    sampleReasoning: 'All 8 items are chai types. They belong together. One list called chai_types can hold all of them and I can add more without creating new variables.',
    effectivenessScore: 97,
    theme: 'chai-stall',
    caseStudyId: 'cs-chai-stall',
    themeStep: 2,
    themeArc: 'Variables → Lists → Dicts → Functions',
    themeEmoji: '🍵'
  },
  {
    title: 'Ramu\'s Price Lookup Problem',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'Ramu now has two parallel lists: chai_types = ["ginger", "masala", ...] and prices = [15, 20, ...]. A customer asks "How much is tulsi?" Ramu has to count to position 4 in one list, then find position 4 in another. He made a mistake yesterday — he reordered the types list but forgot to reorder prices.',
    prompt: 'Ramu lost ₹200 yesterday because his lists got out of sync. He says: "I want to look up a chai by NAME, not by number." What structure lets you store the name AND price together as a pair?',
    objectives: ['Understand why parallel lists break', 'Discover named lookup', 'Map key-value pairs to a dictionary'],
    sampleReasoning: 'A dictionary maps each chai name directly to its price. "tulsi" always points to its correct price — no counting, no sync issues.',
    effectivenessScore: 98,
    theme: 'chai-stall',
    caseStudyId: 'cs-chai-stall',
    themeStep: 3,
    themeArc: 'Variables → Lists → Dicts → Functions',
    themeEmoji: '🍵'
  },
  {
    title: 'Ramu\'s Evening Revenue Calculator',
    difficulty: 'Builder',
    concepts: ['functions'],
    context: 'Every evening, Ramu calculates revenue for each chai type: cups_sold × price. He copy-pasted this calculation 8 times in his notebook — once for each chai. When he raised masala chai price, he had to update 3 different places and still missed one.',
    prompt: 'Ramu says: "I write the same calculation for every single chai type. There has to be a better way." How would you package this repeatable calculation so Ramu writes it ONCE and reuses it for every chai?',
    objectives: ['Identify repeated logic', 'Package it as a reusable process', 'Map the process to a Python function'],
    sampleReasoning: 'A function called calculate_revenue takes cups_sold and price_per_cup, then returns the total. Write once, call it for each chai type.',
    effectivenessScore: 96,
    theme: 'chai-stall',
    caseStudyId: 'cs-chai-stall',
    themeStep: 4,
    themeArc: 'Variables → Lists → Dicts → Functions',
    themeEmoji: '🍵'
  },

  // ─── UADE THEME 2: ISRO MISSION CONTROL ──────────────────────────────────────
  {
    title: 'ISRO: Three Telemetry Variables',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'You are an intern at ISRO\'s Chandrayaan-3 mission control. The spacecraft has three critical readings: altitude (in km), fuel level (in %), and velocity (in m/s). Right now you have three separate variables on your screen.',
    prompt: 'The mission director asks: "What are the three values we must track at all times?" How would you name and store these three critical pieces of mission data?',
    objectives: ['Name critical values meaningfully', 'Understand that names carry meaning in code', 'Store mission-critical data as variables'],
    sampleReasoning: 'altitude_km, fuel_percent, velocity_ms — each name tells exactly what unit and what it measures. Naming matters in space.',
    effectivenessScore: 94,
    theme: 'isro',
    caseStudyId: 'cs-isro',
    themeStep: 1,
    themeArc: 'Variables → Lists → Dicts → Sets → Modules',
    themeEmoji: '🚀'
  },
  {
    title: 'ISRO: Twelve Subsystem Chaos',
    difficulty: 'Explorer',
    concepts: ['lists'],
    context: 'Chandrayaan-3 has 12 subsystems: propulsion, thermal, communication, power, navigation, attitude control, payload, avionics, structure, mechanisms, software, and ground systems. A second intern added three more subsystems without telling you. Now you have 15 separate variables. Someone\'s variable is named temp2 and nobody knows what it means.',
    prompt: 'The mission director is furious: "Why do we have 15 separate variables? One new intern and the whole codebase breaks!" What structure would hold all subsystem names together and survive additions without chaos?',
    objectives: ['Understand chaos from ungrouped variables', 'Group related items under one name', 'Discover lists as a solution to this pain'],
    sampleReasoning: 'A list called subsystems holds all 12 names. Adding a new one is just appending to the list — no new variables, no naming chaos.',
    effectivenessScore: 97,
    theme: 'isro',
    caseStudyId: 'cs-isro',
    themeStep: 2,
    themeArc: 'Variables → Lists → Dicts → Sets → Modules',
    themeEmoji: '🚀'
  },
  {
    title: 'ISRO: FAIL at Position 7',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'It is 2:17 AM. The status board shows: [OK, OK, OK, FAIL, OK, OK, OK, OK, OK, OK, OK, OK]. Subsystem at index 3 failed. But which subsystem IS index 3? You have to mentally count: propulsion=0, thermal=1, communication=2, power=3. It\'s 2 AM. You miscounted twice.',
    prompt: 'The mission director shouts: "I don\'t care about position 3! I need to know which SUBSYSTEM failed by NAME!" What structure would let you look up subsystem status by name, not by position?',
    objectives: ['Feel the danger of position-based lookup', 'Discover named lookup under pressure', 'Map subsystem → status as dictionary'],
    sampleReasoning: 'A dictionary maps each subsystem name to its status. status["power"] = "FAIL" — no counting, no miscount at 2 AM.',
    effectivenessScore: 99,
    theme: 'isro',
    caseStudyId: 'cs-isro',
    themeStep: 3,
    themeArc: 'Variables → Lists → Dicts → Sets → Modules',
    themeEmoji: '🚀'
  },
  {
    title: 'ISRO: Duplicate Telemetry Signals',
    difficulty: 'Explorer',
    concepts: ['sets'],
    context: 'Three ground stations — Bengaluru, Mauritius, and Bhopal — all send telemetry. Due to a relay issue, the Bengaluru station sent the same altitude reading 14 times. Your data array has the same reading repeated across many entries. The average is now wrong.',
    prompt: 'The data scientist says: "We\'re getting duplicate readings from the same timestamp. We need only UNIQUE readings." What structure automatically guarantees that each value appears only once, no matter how many times it is submitted?',
    objectives: ['Understand the cost of duplicates', 'Discover uniqueness as a data property', 'Map uniqueness guarantee to Python sets'],
    sampleReasoning: 'A set only holds unique values. Adding the same altitude reading 14 times still results in one entry. Sets solve the duplicate problem automatically.',
    effectivenessScore: 96,
    theme: 'isro',
    caseStudyId: 'cs-isro',
    themeStep: 4,
    themeArc: 'Variables → Lists → Dicts → Sets → Modules',
    themeEmoji: '🚀'
  },

  // ─── UADE THEME 3: THE VIRAL INSTAGRAM FILTER CREATOR ────────────────────────
  {
    title: 'Filter App: The First Variable',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'You are building a photo filter app. Right now you have one filter: "Warm Vintage." It has one setting: brightness (set to 1.3 by default).',
    prompt: 'Your app has one setting for one filter. How do you store that brightness value so you can use it to process the photo?',
    objectives: ['Store a single filter setting', 'Name it meaningfully', 'Understand how naming connects to usage'],
    sampleReasoning: 'brightness = 1.3 — a named variable holds the setting and can be referenced whenever the filter is applied.',
    effectivenessScore: 91,
    theme: 'instagram',
    caseStudyId: 'cs-instagram',
    themeStep: 1,
    themeArc: 'Variables → Lists → Dicts → Functions → Classes',
    themeEmoji: '📸'
  },
  {
    title: 'Filter App: Twenty Filters, Twenty Variables',
    difficulty: 'Explorer',
    concepts: ['lists'],
    context: 'Your filter app now has 20 filters: Warm Vintage, Neon Dreams, Faded Film, Ocean Breeze... You have 20 separate variables: filter1, filter2... filter20. Users swipe through filters. When they swipe right to filter number 7, your code tries to access filter7 — but you can\'t swipe to a variable name.',
    prompt: 'A friend tries your app and says: "Swiping is broken — I can only see the first filter." Your code cannot loop over 20 separate variables. What single structure would hold all 20 filter names so your swipe gesture can navigate them by position?',
    objectives: ['Understand that variables cannot be iterated', 'Discover that lists enable position-based navigation', 'Connect swiping to list indexing'],
    sampleReasoning: 'A list called filters holds all 20 names. swipe_right moves the index forward by 1. filters[current_index] gives the active filter.',
    effectivenessScore: 97,
    theme: 'instagram',
    caseStudyId: 'cs-instagram',
    themeStep: 2,
    themeArc: 'Variables → Lists → Dicts → Functions → Classes',
    themeEmoji: '📸'
  },
  {
    title: 'Filter App: Five Settings Per Filter',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'Each filter now has 5 settings: brightness, contrast, saturation, hue_shift, and grain. You have 5 parallel lists: brightness_list[7], contrast_list[7], saturation_list[7]... You updated the brightness list for "Neon Dreams" but forgot to update the contrast list. The filter looks broken.',
    prompt: 'You wasted 3 hours debugging because your 5 lists got out of sync. A mentor says: "What if each filter was ONE complete package with all its settings together?" What structure bundles multiple named settings into a single unit?',
    objectives: ['Feel the pain of parallel lists diverging', 'Discover bundling related data together', 'Map a filter\'s settings to a dictionary'],
    sampleReasoning: 'A dictionary for each filter: {"brightness": 1.3, "contrast": 1.1, "saturation": 1.4, "hue_shift": 10, "grain": 0.2}. All settings travel together — they can\'t fall out of sync.',
    effectivenessScore: 98,
    theme: 'instagram',
    caseStudyId: 'cs-instagram',
    themeStep: 3,
    themeArc: 'Variables → Lists → Dicts → Functions → Classes',
    themeEmoji: '📸'
  },
  {
    title: 'Filter App: Copy-Paste Logic Breaks',
    difficulty: 'Builder',
    concepts: ['functions'],
    context: 'You apply filters by copy-pasting the same apply_filter logic for each of your 20 filters. When you want to add a "fade" effect that dims the edges, you have to add it in 20 places. You added it in 19 places and forgot filter number 14. Users are complaining that "Moody Cinema" doesn\'t fade.',
    prompt: 'A senior dev looks at your code and says: "You have the same 15 lines copied 20 times. If you change anything, you\'ll miss one. EVERY time." How would you package the apply-filter logic so you write it once and it works for every filter?',
    objectives: ['Experience the maintenance nightmare of copy-pasted logic', 'Understand DRY: Don\'t Repeat Yourself', 'Package repeatable logic as a function'],
    sampleReasoning: 'def apply_filter(photo, filter_settings): takes a photo and a filter dict, applies all settings, returns the modified photo. Called once per filter — no copy-paste.',
    effectivenessScore: 96,
    theme: 'instagram',
    caseStudyId: 'cs-instagram',
    themeStep: 4,
    themeArc: 'Variables → Lists → Dicts → Functions → Classes',
    themeEmoji: '📸'
  },

  // ─── UADE THEME 4: MIDNIGHT FOOD DELIVERY STARTUP ────────────────────────────
  {
    title: 'Hostel Startup: One Item, Two Variables',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'It is 2 AM in a hostel room. Three friends — Arjun, Meera, and Dev — just launched "HungerFix," a food delivery app for their campus. They have exactly one item: Maggi. Price: ₹30.',
    prompt: 'The friends need the app to remember what they sell and for how much. What are the two pieces of information they absolutely need to store, and how would you name them clearly?',
    objectives: ['Identify the minimum data needed', 'Name variables descriptively', 'Understand that variables hold the state of the app'],
    sampleReasoning: 'item_name = "Maggi" and item_price = 30. Simple, named, and the whole app can reference these two values.',
    effectivenessScore: 93,
    theme: 'food-delivery',
    caseStudyId: 'cs-food-delivery',
    themeStep: 1,
    themeArc: 'Variables → Lists → Dicts → Sets → try/except',
    themeEmoji: '🍕'
  },
  {
    title: 'Hostel Startup: Fifteen Items, No Search',
    difficulty: 'Explorer',
    concepts: ['lists'],
    context: 'By night 3, HungerFix has 15 items: Maggi, Bread-Omelette, Poha, Upma, Vada Pav... Users are texting "Do you have Poha?" Arjun has to scroll through 15 separate variables to check. He also cannot display a menu — you can\'t print 15 separate variables in a loop.',
    prompt: 'Dev says: "We can\'t even show users a menu because we have 15 variables. I can\'t loop over variables!" What structure would let you store all 15 items so you can loop through them, display them, and search them?',
    objectives: ['Understand that iteration requires a collection', 'Discover that loops need lists', 'Connect menu display to list traversal'],
    sampleReasoning: 'menu = ["Maggi", "Bread-Omelette", "Poha", ...]. Now for item in menu: print(item) displays the whole menu. And "Poha" in menu checks availability instantly.',
    effectivenessScore: 96,
    theme: 'food-delivery',
    caseStudyId: 'cs-food-delivery',
    themeStep: 2,
    themeArc: 'Variables → Lists → Dicts → Sets → try/except',
    themeEmoji: '🍕'
  },
  {
    title: 'Hostel Startup: The Duplicate Biryani Crisis',
    difficulty: 'Explorer',
    concepts: ['sets'],
    context: 'Night 10. Two friends — Ananya and Rohan — both order the last biryani at 11:58 PM simultaneously. Both orders go through. The friends running the stall have only ONE biryani. They cook two. Costs double. One customer still waits.',
    prompt: 'Meera says: "We need to track active orders, but we can\'t allow the SAME item to be ordered twice if only one is in stock." What structure would automatically prevent the same order from appearing twice — no manual checking needed?',
    objectives: ['Understand the cost of duplicates in real systems', 'Discover sets as a membership uniqueness guarantee', 'Apply set membership to order deduplication'],
    sampleReasoning: 'active_orders = set(). When Ananya orders biryani: if "biryani" not in active_orders, add it. When Rohan orders: "biryani" is already in the set — reject it. Sets prevent duplicates automatically.',
    effectivenessScore: 97,
    theme: 'food-delivery',
    caseStudyId: 'cs-food-delivery',
    themeStep: 3,
    themeArc: 'Variables → Lists → Dicts → Sets → try/except',
    themeEmoji: '🍕'
  },
  {
    title: 'Hostel Startup: The Crashed Order History',
    difficulty: 'Builder',
    concepts: ['error handling', 'try/except'],
    context: 'Night 14. A user types a quantity of -3 samosas. The app tries to calculate the bill: -3 × ₹12 = -₹36. The app charges them NEGATIVE money and then crashes trying to write to the orders file. The crash wipes the entire order history. 47 orders gone.',
    prompt: 'Dev stares at the empty orders file at 3 AM and says: "A user broke our app with a negative number. We had no plan for this." How would you build a safety net that catches bad input BEFORE it reaches the calculation and file-write — so the app never crashes and data is never lost?',
    objectives: ['Understand that real programs receive unexpected input', 'Discover defensive programming', 'Map error catching to try/except'],
    sampleReasoning: 'Wrap the quantity input and bill calculation in a try block. If quantity is negative, raise a ValueError. The except block shows the user an error without crashing — and the order history is never touched.',
    effectivenessScore: 98,
    theme: 'food-delivery',
    caseStudyId: 'cs-food-delivery',
    themeStep: 4,
    themeArc: 'Variables → Lists → Dicts → Sets → try/except',
    themeEmoji: '🍕'
  },

  // ─── UADE THEME 5: THE AI PLAYLIST ────────────────────────────────────────────
  {
    title: 'Playlist: One Mood, One Genre',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'You are building an app that learns your music taste. Right now it knows one thing: your current mood. When you\'re in a "study" mood, it plays lo-fi. One mood, one genre.',
    prompt: 'The app needs to remember what mood you are in right now. How would you store the current mood so the app can decide what to play?',
    objectives: ['Store state as a variable', 'Understand that apps need to remember things', 'Connect variable to decision-making'],
    sampleReasoning: 'current_mood = "study" — one variable holds the current state, and the app can check it to select a playlist.',
    effectivenessScore: 90,
    theme: 'ai-playlist',
    caseStudyId: 'cs-ai-playlist',
    themeStep: 1,
    themeArc: 'Variables → Lists → Loops → Sets → Dicts → Functions',
    themeEmoji: '🎵'
  },
  {
    title: 'Playlist: Twelve Genres, No Loop',
    difficulty: 'Explorer',
    concepts: ['lists', 'loops'],
    context: 'Your app now knows 12 genres you love: lo-fi, jazz, indie, classical, synthwave, ambient, folk, blues, punk, metal, hip-hop, and bossa nova. You have 12 separate variables. The recommendation engine needs to check all of them. You\'re writing: check_genre1(), check_genre2()... twelve times.',
    prompt: 'Your code has 12 separate function calls — one for each genre. Adding a 13th genre means adding another line. The recommendation logic cannot adapt dynamically. What structure lets you loop through all genres with a single repeated action?',
    objectives: ['Understand that repetitive calls need loops', 'Discover that lists enable dynamic iteration', 'Connect recommendation loop to list traversal'],
    sampleReasoning: 'genres = ["lo-fi", "jazz", ...]. for genre in genres: check_genre(genre) — one loop handles 12 or 1200 genres. Adding a new genre is one append.',
    effectivenessScore: 95,
    theme: 'ai-playlist',
    caseStudyId: 'cs-ai-playlist',
    themeStep: 2,
    themeArc: 'Variables → Lists → Loops → Sets → Dicts → Functions',
    themeEmoji: '🎵'
  },
  {
    title: 'Playlist: Shape of You, Again',
    difficulty: 'Explorer',
    concepts: ['sets'],
    context: 'Your recommendation engine keeps surfacing "Shape of You" — you\'ve rated it 4 stars and it keeps showing up. You\'ve heard it 23 times this week. Your recently_played list has the same 5 songs repeated across 200 entries.',
    prompt: 'You tell the app: "I want variety. Never play the same song twice in one session." The recently_played list doesn\'t prevent repeats because lists allow duplicates. What structure would automatically guarantee that each song in a session appears exactly once, no matter how many times the engine tries to add it?',
    objectives: ['Experience the frustration of duplicates in recommendations', 'Discover sets as a uniqueness enforcer', 'Apply sets to deduplication of a playlist'],
    sampleReasoning: 'session_played = set(). When the engine picks a song, check: if song not in session_played, play it and add to the set. Sets reject duplicates — "Shape of You" gets added once and stays there.',
    effectivenessScore: 96,
    theme: 'ai-playlist',
    caseStudyId: 'cs-ai-playlist',
    themeStep: 3,
    themeArc: 'Variables → Lists → Loops → Sets → Dicts → Functions',
    themeEmoji: '🎵'
  },
  {
    title: 'Playlist: Storing Play Count AND Rating',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'The app needs to remember two things per song: how many times you played it, and what you rated it (1–5 stars). You have two parallel lists: play_counts[i] and ratings[i]. You sorted one list by count and forgot to sort the other. A song shows a 5-star rating next to the wrong play count.',
    prompt: 'Your recommendation score is wrong because the two lists got out of sync again. A friend suggests: "What if each song carried all its own information — play count AND rating — as one complete package?" What structure bundles multiple named values for one song together?',
    objectives: ['Experience sync failure of parallel lists', 'Discover that dictionaries bundle related data', 'Map a song\'s stats to a dictionary'],
    sampleReasoning: 'songs = {"Shape of You": {"play_count": 23, "rating": 4}}. The song carries its own data. Sort by play_count? The rating comes along automatically.',
    effectivenessScore: 97,
    theme: 'ai-playlist',
    caseStudyId: 'cs-ai-playlist',
    themeStep: 4,
    themeArc: 'Variables → Lists → Loops → Sets → Dicts → Functions',
    themeEmoji: '🎵'
  },

  // ─── UADE THEME 6: THE KOTA COACHING FACTORY ──────────────────────────────────
  {
    title: 'Kota: Your JEE Rank Variable',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'You are a JEE aspirant at a Kota coaching center. You just got your mock test rank: 4,217. That\'s your current rank. Everything in your day — which batch you\'re in, which counselor you see — depends on this one number.',
    prompt: 'The coaching center\'s system needs to store your rank so it can decide your batch placement. What would you call this piece of information, and why does the name matter?',
    objectives: ['Store a single important value', 'Choose a meaningful name over a generic one', 'Understand how names convey intent'],
    sampleReasoning: 'my_jee_rank = 4217 — the name tells anyone reading the code exactly what this number represents. rank = 4217 is fine, but x = 4217 tells you nothing.',
    effectivenessScore: 92,
    theme: 'kota',
    caseStudyId: 'cs-kota',
    themeStep: 1,
    themeArc: 'Variables → Lists → Dicts → Sorting → Nested structures',
    themeEmoji: '📚'
  },
  {
    title: 'Kota: Thirty Batchmates, Thirty Variables',
    difficulty: 'Explorer',
    concepts: ['lists'],
    context: 'Your batch has 30 students. The director wants the batch average rank. You have 30 separate variables: rank_arjun, rank_priya, rank_dev... To calculate the average, you add all 30 variables manually. A new student joins — you add rank_newstudent and forget to include them in the average calculation.',
    prompt: 'The director asks: "Why does adding one student break the average?" The answer is: you are manually managing 30 separate names. What structure would let you add a new rank in ONE place and have the average work automatically?',
    objectives: ['Feel the fragility of ungrouped data', 'Discover that collections allow dynamic computation', 'Connect list to automatic aggregate operations'],
    sampleReasoning: 'batch_ranks = [4217, 2891, 6043, ...]. To add a student: batch_ranks.append(new_rank). Average: sum(batch_ranks) / len(batch_ranks). Automatic — no manual updates.',
    effectivenessScore: 96,
    theme: 'kota',
    caseStudyId: 'cs-kota',
    themeStep: 2,
    themeArc: 'Variables → Lists → Dicts → Sorting → Nested structures',
    themeEmoji: '📚'
  },
  {
    title: 'Kota: Find Priya\'s Rank by Name',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'A parent calls and asks: "What is Priya Sharma\'s rank?" You have a list of 30 ranks. You have to find which position Priya is at, then look up that position in the rank list. The director is watching. It takes 40 seconds.',
    prompt: 'The director says: "In a real coaching center, I need to look up any student\'s rank by NAME — not by finding their position first." What structure maps each student\'s name directly to their rank?',
    objectives: ['Experience slow sequential lookup under pressure', 'Discover named direct lookup', 'Map student → rank as a dictionary'],
    sampleReasoning: 'ranks = {"Priya Sharma": 2891, "Arjun Dev": 4217, ...}. ranks["Priya Sharma"] gives her rank immediately — no searching needed.',
    effectivenessScore: 97,
    theme: 'kota',
    caseStudyId: 'cs-kota',
    themeStep: 3,
    themeArc: 'Variables → Lists → Dicts → Sorting → Nested structures',
    themeEmoji: '📚'
  },
  {
    title: 'Kota: The Merit List Algorithm',
    difficulty: 'Builder',
    concepts: ['sorting', 'dictionaries', 'algorithms'],
    context: 'The director wants the top 10 students for the merit scholarship. You have ranks = {"Priya": 2891, "Arjun": 4217, ...}. Lower rank number = better performance. You need to sort by rank value, handle ties, and take the top 10.',
    prompt: 'The director says: "I need the merit list NOW — sorted by rank, ties broken by name alphabetically, top 10 only." What sequence of reasoning steps turns the dictionary into a sorted, trimmed merit list?',
    objectives: ['Understand sorting as an algorithm, not magic', 'Sort a dictionary by value', 'Slice a result to a required size'],
    sampleReasoning: 'Sort the dictionary items by rank value (ascending), then alphabetically for ties. sorted(ranks.items(), key=lambda x: (x[1], x[0]))[:10] gives the top 10 merit list.',
    effectivenessScore: 95,
    theme: 'kota',
    caseStudyId: 'cs-kota',
    themeStep: 4,
    themeArc: 'Variables → Lists → Dicts → Sorting → Nested structures',
    themeEmoji: '📚'
  },

  // ─── POTTERHEADS THEME SCENARIOS ───────────────────────────────────────────
  {
    title: 'Potion Ingredient Dosage',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'Severus Snape asks you to measure Boomslang Skin for Polyjuice Potion.',
    prompt: 'How would you store the weight in grams so your cauldron brewing notes remember it?',
    objectives: ['Identify single value', 'Assign a clear name', 'Understand variable storage'],
    sampleReasoning: 'boomslang_weight = 25 — store the exact weight in a named variable to use in the recipe.',
    effectivenessScore: 96,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-potions',
    themeStep: 1,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Spellbook Spell List',
    difficulty: 'Beginner',
    concepts: ['lists'],
    context: 'Harry Potter wants to keep track of all defensive spells learned in DADA class.',
    prompt: 'How would you group "Expelliarmus", "Stupefy", and "Protego" into a single structure?',
    objectives: ['Group spells together', 'Recognize list ordering', 'Map spells to a list'],
    sampleReasoning: 'defense_spells = ["Expelliarmus", "Stupefy", "Protego"] — keep them in one list for fast casting access.',
    effectivenessScore: 97,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-potions',
    themeStep: 2,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'House Point Counter',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'Professor McGonagall needs to track House Points for Gryffindor, Slytherin, Ravenclaw, and Hufflepuff.',
    prompt: 'How would you store each house name directly paired with its score?',
    objectives: ['Map house to score', 'Enable direct lookup', 'Use a dictionary'],
    sampleReasoning: 'house_points = {"Gryffindor": 450, "Slytherin": 420, "Ravenclaw": 390, "Hufflepuff": 380} maps house names to scores directly.',
    effectivenessScore: 98,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-potions',
    themeStep: 3,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Cauldron Stirring Helper',
    difficulty: 'Builder',
    concepts: ['functions'],
    context: 'Brewing Felix Felicis requires clockwise stirring every 3 minutes.',
    prompt: 'How would you design a reusable helper function that calculates total stirs required?',
    objectives: ['Create reusable brewing logic', 'Accept duration parameter', 'Return stir count'],
    sampleReasoning: 'def calculate_stirs(minutes): return minutes * 4 — write once and reuse for any potion recipe.',
    effectivenessScore: 96,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-potions',
    themeStep: 4,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Unforgivable Curse Deduplicator',
    difficulty: 'Explorer',
    concepts: ['sets'],
    context: 'The Ministry of Magic receives duplicate dark magic spell reports from multiple owls.',
    prompt: 'How would you automatically ensure each reported spell is unique with no duplicates?',
    objectives: ['Eliminate duplicate reports', 'Guarantee uniqueness', 'Map to Python sets'],
    sampleReasoning: 'dark_spells = set(owl_reports) automatically removes duplicates.',
    effectivenessScore: 95,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-spells',
    themeStep: 1,
    themeEmoji: '🪄'
  },

  // ─── MARVEL THEME SCENARIOS ────────────────────────────────────────────────
  {
    title: 'Arc Reactor Output Voltage',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'Tony Stark needs J.A.R.V.I.S. to monitor the Mark 85 Arc Reactor power level.',
    prompt: 'How would you store the current voltage percentage in code?',
    objectives: ['Identify critical suit value', 'Store in named variable', 'Reference during combat'],
    sampleReasoning: 'reactor_voltage = 98.5 — keep suit power level in a named variable.',
    effectivenessScore: 96,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 1,
    themeEmoji: '🦾'
  },
  {
    title: 'Avengers Emergency Roster',
    difficulty: 'Beginner',
    concepts: ['lists'],
    context: 'Captain America calls an emergency assembly for Iron Man, Thor, Hulk, and Spider-Man.',
    prompt: 'How would you store all active Avengers together so J.A.R.V.I.S. can alert them in order?',
    objectives: ['Group hero names', 'Maintain assembly order', 'Store as a list'],
    sampleReasoning: 'active_avengers = ["Iron Man", "Thor", "Hulk", "Spider-Man"] stores heroes in a single list.',
    effectivenessScore: 97,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 2,
    themeEmoji: '🦾'
  },
  {
    title: 'J.A.R.V.I.S. Weapon Diagnostics',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'Tony Stark asks: "J.A.R.V.I.S., check status of repulsors, unibeam, and nanotech shield!"',
    prompt: 'How would you map each weapon system name directly to its operational status?',
    objectives: ['Map weapon to status', 'Instant direct lookup', 'Store as dictionary'],
    sampleReasoning: 'weapon_status = {"repulsors": "READY", "unibeam": "CHARGING", "shield": "ACTIVE"} allows instant lookup by name.',
    effectivenessScore: 98,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 3,
    themeEmoji: '🦾'
  },
  {
    title: 'Repulsor Thrust Calculator',
    difficulty: 'Builder',
    concepts: ['functions'],
    context: 'Iron Man needs to compute flight trajectory thruster force based on suit weight and speed.',
    prompt: 'How would you package this flight calculation into a reusable function for J.A.R.V.I.S.?',
    objectives: ['Package thruster math', 'Accept weight and velocity', 'Return force value'],
    sampleReasoning: 'def calculate_thrust(weight, speed): return weight * speed * 1.5 — reuse across all armor marks.',
    effectivenessScore: 96,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 4,
    themeEmoji: '🦾'
  },
  {
    title: 'Infinity Stone Energy Signature Filter',
    difficulty: 'Explorer',
    concepts: ['sets'],
    context: 'Sensors in Wakanda register cosmic energy spikes. Multiple sensors detect the Space Stone signature.',
    prompt: 'How would you remove duplicate sensor readings to get only unique stone signatures?',
    objectives: ['Deduplicate sensor readings', 'Guarantee unique signatures', 'Map to sets'],
    sampleReasoning: 'unique_signatures = set(sensor_spikes) guarantees unique cosmic signals.',
    effectivenessScore: 95,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-infinity',
    themeStep: 1,
    themeEmoji: '💎'
  },

  // ─── ANIME THEME SCENARIOS ─────────────────────────────────────────────────
  {
    title: 'Chakra Points Tracker',
    difficulty: 'Beginner',
    concepts: ['variables'],
    context: 'Naruto is practicing Nine-Tails Chakra control and needs to track his reserve points.',
    prompt: 'How would you store Naruto\'s current chakra level in a single variable?',
    objectives: ['Identify chakra value', 'Name variable clearly', 'Store for Jutsu casting'],
    sampleReasoning: 'chakra_points = 5000 — store current chakra in a named variable.',
    effectivenessScore: 96,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 1,
    themeEmoji: '⚔️'
  },
  {
    title: 'Hidden Leaf Squad Roster',
    difficulty: 'Beginner',
    concepts: ['lists'],
    context: 'Kakashi Sensei forms Squad 7 with Naruto, Sasuke, and Sakura.',
    prompt: 'How would you group all three shinobi into a single list for mission deployment?',
    objectives: ['Group squad members', 'Maintain ninja order', 'Store in a list'],
    sampleReasoning: 'squad_7 = ["Naruto", "Sasuke", "Sakura"] keeps the team together in one list.',
    effectivenessScore: 97,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 2,
    themeEmoji: '⚔️'
  },
  {
    title: 'Jutsu Hand Sign Vault',
    difficulty: 'Explorer',
    concepts: ['dictionaries'],
    context: 'The Shinobi Library stores hand sign sequences for Rasengan, Chidori, and Shadow Clone jutsu.',
    prompt: 'How would you map each Jutsu name to its required hand sign combination?',
    objectives: ['Map jutsu to hand signs', 'Look up jutsu instantly', 'Store as dictionary'],
    sampleReasoning: 'jutsu_vault = {"Rasengan": "Ram → Serpent", "Chidori": "Ox → Rabbit → Monkey"} maps jutsu directly to signs.',
    effectivenessScore: 98,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 3,
    themeEmoji: '⚔️'
  },
  {
    title: 'Shadow Clone Multiplier',
    difficulty: 'Builder',
    concepts: ['functions'],
    context: 'Naruto wants to calculate total chakra consumed when creating N shadow clones.',
    prompt: 'How would you write a reusable function to compute total chakra cost per clone count?',
    objectives: ['Create clone chakra formula', 'Accept clone count', 'Return total chakra required'],
    sampleReasoning: 'def clone_chakra(clone_count): return clone_count * 50 — calculate chakra cost dynamically.',
    effectivenessScore: 96,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 4,
    themeEmoji: '⚔️'
  },
  {
    title: 'Dungeon Rift Monster Index',
    difficulty: 'Explorer',
    concepts: ['sets'],
    context: 'An S-Rank Hunter encounters wild monsters in a dungeon rift and receives duplicate radar pings.',
    prompt: 'How would you filter out duplicate monster pings to index only unique species?',
    objectives: ['Filter duplicate pings', 'Store unique species', 'Map to sets'],
    sampleReasoning: 'unique_monsters = set(radar_pings) removes duplicate dungeon pings.',
    effectivenessScore: 95,
    theme: 'anime',
    caseStudyId: 'cs-anime-pokedex',
    themeStep: 1,
    themeEmoji: '🐉'
  },

  // ─── POTTERHEADS EXTENDED CHAPTER SCENARIOS ──────────────────────────────
  {
    title: 'Gryffindor House Points Addition',
    difficulty: 'Beginner',
    concepts: ['arithmetic', 'subtraction'],
    context: 'Harry scores 50 points for catching the Snitch, but Snape deducts 15 for being late.',
    prompt: 'How would you calculate Gryffindor\'s net points using arithmetic operators?',
    objectives: ['Perform addition and subtraction', 'Calculate net points', 'Use math operators'],
    sampleReasoning: 'net_points = 50 - 15 calculates the final house points.',
    effectivenessScore: 94,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-spells',
    themeStep: 2,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Spell Incantation Generator',
    difficulty: 'Beginner',
    concepts: ['strings'],
    context: 'Hermione wants to construct full spell commands like "Harry casts Expelliarmus!".',
    prompt: 'How would you combine the wizard\'s name and the spell name into a single message?',
    objectives: ['Combine text strings', 'Format incantations', 'Map to Python strings'],
    sampleReasoning: 'incantation = f"{wizard} casts {spell}!" sticks text pieces together.',
    effectivenessScore: 95,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-spells',
    themeStep: 3,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Sorting Hat House Evaluator',
    difficulty: 'Beginner',
    concepts: ['conditionals', 'comparisons'],
    context: 'The Sorting Hat checks a student\'s bravery and wisdom scores to decide their house.',
    prompt: 'How would you write a decision rule to assign Gryffindor or Ravenclaw based on scores?',
    objectives: ['Compare trait scores', 'Branch decisions', 'Map to if/else'],
    sampleReasoning: 'if bravery >= 80: house = "Gryffindor" else if wisdom >= 80: house = "Ravenclaw".',
    effectivenessScore: 96,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-spells',
    themeStep: 4,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Cauldron Clockwise Stir Routine',
    difficulty: 'Explorer',
    concepts: ['loops', 'while loops'],
    context: 'Brewing Felix Felicis requires stirring the potion cauldron clockwise exactly 50 times.',
    prompt: 'How would you make Python repeat the stirring action 50 times automatically?',
    objectives: ['Identify repeated stir action', 'Loop stir count', 'Map to for/while loop'],
    sampleReasoning: 'for stir in range(1, 51): print(f"Stir {stir}") repeats the action automatically.',
    effectivenessScore: 95,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-potions',
    themeStep: 5,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Restricted Section Scroll Search',
    difficulty: 'Explorer',
    concepts: ['search', 'filtering'],
    context: 'Harry is searching through 100 library scrolls to locate a forbidden dark magic spell.',
    prompt: 'How would you filter the scroll list to find only scrolls containing "Dark Magic"?',
    objectives: ['Scan list items', 'Filter by keyword', 'Map to search/filtering'],
    sampleReasoning: 'dark_scrolls = [scroll for scroll in library if "Dark" in scroll] filters the scrolls.',
    effectivenessScore: 94,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-spells',
    themeStep: 5,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Exploding Cauldron Exception Shield',
    difficulty: 'Builder',
    concepts: ['error handling', 'try except'],
    context: 'A potion heat spikes above 300 degrees and threatens to blow up the potions dungeon.',
    prompt: 'How would you catch this overheating error so your code casts a shield charm instead of crashing?',
    objectives: ['Detect heat overload', 'Catch exception', 'Map to try/except'],
    sampleReasoning: 'try: brew_potion() except OverheatError: cast_shield() prevents a crash.',
    effectivenessScore: 97,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-potions',
    themeStep: 6,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Triwizard Tournament Leaderboard Ranker',
    difficulty: 'Builder',
    concepts: ['algorithms', 'sorting'],
    context: 'Dumbledore needs to sort the final Triwizard scores from highest to lowest score.',
    prompt: 'How would you order champion scores from highest to lowest?',
    objectives: ['Order champion scores', 'Sort list descending', 'Map to sorting algorithms'],
    sampleReasoning: 'scores.sort(reverse=True) ranks the champions in descending order.',
    effectivenessScore: 96,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-spells',
    themeStep: 6,
    themeEmoji: '🧙‍♂️'
  },
  {
    title: 'Ministry Secret Archive Scroll Log',
    difficulty: 'Builder',
    concepts: ['files', 'file io'],
    context: 'The Ministry of Magic wants to save all recorded spell logs into a permanent parchment file.',
    prompt: 'How would you write text into a file so it stays saved even after shutting down your laptop?',
    objectives: ['Open file for writing', 'Save spell logs', 'Map to file I/O'],
    sampleReasoning: 'with open("spells.txt", "w") as f: f.write(log) saves data permanently.',
    effectivenessScore: 95,
    theme: 'potterheads',
    caseStudyId: 'cs-potter-spells',
    themeStep: 7,
    themeEmoji: '🧙‍♂️'
  },

  // ─── MARVEL THEME EXTENDED SCENARIOS ───────────────────────────────────────
  {
    title: 'Suit Power Drain Calculator',
    difficulty: 'Beginner',
    concepts: ['arithmetic', 'subtraction'],
    context: 'Iron Man has 1000 kW power. Repulsor blasts use 250 kW and shield uses 180 kW.',
    prompt: 'How would you compute the remaining suit energy using subtraction operators?',
    objectives: ['Subtract power drain', 'Calculate remaining energy', 'Use arithmetic operators'],
    sampleReasoning: 'remaining = 1000 - 250 - 180 calculates power remaining.',
    effectivenessScore: 94,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 5,
    themeEmoji: '🦾'
  },
  {
    title: 'J.A.R.V.I.S. Audio Broadcast Formatter',
    difficulty: 'Beginner',
    concepts: ['strings'],
    context: 'J.A.R.V.I.S. needs to construct HUD alert strings like "Warning Mr. Stark: Thruster #2 Low".',
    prompt: 'How would you format variables into a clear status text string?',
    objectives: ['Format status message', 'Combine variables with text', 'Map to strings'],
    sampleReasoning: 'alert = f"Warning {user}: {system} {status}" formats HUD alerts.',
    effectivenessScore: 95,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 6,
    themeEmoji: '🦾'
  },
  {
    title: 'Nanotech Threat Level Defense Protocol',
    difficulty: 'Beginner',
    concepts: ['conditionals', 'comparisons'],
    context: 'Mark 85 sensors evaluate hostile threat score from 0 to 100.',
    prompt: 'How would you deploy nanotech shields if threat > 80, repulsors if > 50, or scan only?',
    objectives: ['Evaluate threat score', 'Branch suit defense', 'Map to if/elif/else'],
    sampleReasoning: 'if threat > 80: deploy_shield() elif threat > 50: deploy_repulsors().',
    effectivenessScore: 96,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 7,
    themeEmoji: '🦾'
  },
  {
    title: 'Iron Man Subsystem Thruster Diagnostics',
    difficulty: 'Explorer',
    concepts: ['loops', 'while loops'],
    context: 'J.A.R.V.I.S. needs to check all 100 thruster nodes across the armor one by one.',
    prompt: 'How would you repeat the diagnostic check for every thruster node automatically?',
    objectives: ['Iterate thruster nodes', 'Perform check per node', 'Map to loops'],
    sampleReasoning: 'for thruster in armor_thrusters: check_status(thruster) repeats for all nodes.',
    effectivenessScore: 95,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 8,
    themeEmoji: '🦾'
  },
  {
    title: 'Vibranium Radar Signature Scan',
    difficulty: 'Explorer',
    concepts: ['search', 'filtering'],
    context: 'Wakanda radar receives satellite pings across Earth. You need to find all "Vibranium" pings.',
    prompt: 'How would you search radar readings and filter out non-vibranium signals?',
    objectives: ['Filter radar pings', 'Extract matching signals', 'Map to search/filter'],
    sampleReasoning: 'vibranium_pings = [p for p in radar_pings if "Vibranium" in p] filters radar data.',
    effectivenessScore: 94,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-infinity',
    themeStep: 2,
    themeEmoji: '💎'
  },
  {
    title: 'Arc Reactor Power Overload Bypass',
    difficulty: 'Builder',
    concepts: ['error handling', 'try except'],
    context: 'An enemy blast causes Arc Reactor energy voltage to surge above 1200V.',
    prompt: 'How would you handle this voltage surge exception so J.A.R.V.I.S. diverts power to heat sinks without shutting down?',
    objectives: ['Detect power surge', 'Catch voltage error', 'Map to try/except'],
    sampleReasoning: 'try: fire_unibeam() except PowerSurge: divert_to_heatsink() handles surges.',
    effectivenessScore: 97,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 9,
    themeEmoji: '🦾'
  },
  {
    title: 'Stark Satellite Threat Priority Ranker',
    difficulty: 'Builder',
    concepts: ['algorithms', 'sorting'],
    context: 'Stark satellite defense detects 5 incoming alien ships with different danger ratings.',
    prompt: 'How would you sort the incoming ships from highest threat score to lowest?',
    objectives: ['Order threat levels', 'Sort list descending', 'Map to sorting algorithms'],
    sampleReasoning: 'ships.sort(key=lambda s: s.threat, reverse=True) prioritizes targets.',
    effectivenessScore: 96,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-infinity',
    themeStep: 3,
    themeEmoji: '💎'
  },
  {
    title: 'Stark Telemetry Mission Log Archiver',
    difficulty: 'Builder',
    concepts: ['files', 'file io'],
    context: 'J.A.R.V.I.S. must save flight telemetry and battle statistics into a permanent log file.',
    prompt: 'How would you write flight telemetry data into a JSON file for permanent storage?',
    objectives: ['Open file for writing', 'Serialize telemetry data', 'Map to file I/O'],
    sampleReasoning: 'with open("flight_log.json", "w") as f: json.dump(log_data, f) saves telemetry.',
    effectivenessScore: 95,
    theme: 'marvel',
    caseStudyId: 'cs-marvel-jarvis',
    themeStep: 10,
    themeEmoji: '🦾'
  },

  // ─── ANIME THEME EXTENDED SCENARIOS ────────────────────────────────────────
  {
    title: 'Shadow Clone Chakra Cost Calculator',
    difficulty: 'Beginner',
    concepts: ['arithmetic', 'subtraction'],
    context: 'Naruto has 9000 chakra. Creating 10 shadow clones uses 1500 chakra.',
    prompt: 'How would you compute Naruto\'s remaining chakra using subtraction?',
    objectives: ['Subtract chakra spent', 'Compute remaining chakra', 'Use math operators'],
    sampleReasoning: 'remaining = 9000 - 1500 calculates remaining chakra.',
    effectivenessScore: 94,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 5,
    themeEmoji: '⚔️'
  },
  {
    title: 'Jutsu Invocation Scroll Formatter',
    difficulty: 'Beginner',
    concepts: ['strings'],
    context: 'A shinobi scroll needs to generate jutsu announcements like "Naruto unleashes Rasengan!".',
    prompt: 'How would you format the ninja name and jutsu name into an incantation string?',
    objectives: ['Combine text strings', 'Format jutsu incantations', 'Map to strings'],
    sampleReasoning: 'announcement = f"{ninja} unleashes {jutsu}!" formats the scroll text.',
    effectivenessScore: 95,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 6,
    themeEmoji: '⚔️'
  },
  {
    title: 'Chunin Exam Promotion Evaluator',
    difficulty: 'Beginner',
    concepts: ['conditionals', 'comparisons'],
    context: 'Proctors check shinobi exam marks: score >= 85 is Chunin, score >= 60 is Genin.',
    prompt: 'How would you write a decision rule to determine the ninja rank based on score?',
    objectives: ['Compare exam score', 'Branch rank results', 'Map to if/elif/else'],
    sampleReasoning: 'if score >= 85: rank = "Chunin" elif score >= 60: rank = "Genin".',
    effectivenessScore: 96,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 7,
    themeEmoji: '⚔️'
  },
  {
    title: 'Parallel Shadow Clone Training Reps',
    difficulty: 'Explorer',
    concepts: ['loops', 'while loops'],
    context: 'Naruto summons 100 shadow clones to practice tree-climbing training reps simultaneously.',
    prompt: 'How would you repeat the training step for every shadow clone in code?',
    objectives: ['Iterate shadow clones', 'Perform training action', 'Map to loops'],
    sampleReasoning: 'for clone in range(1, 101): train_clone(clone) repeats for all clones.',
    effectivenessScore: 95,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 8,
    themeEmoji: '⚔️'
  },
  {
    title: 'S-Rank Dungeon Boss Finder',
    difficulty: 'Explorer',
    concepts: ['search', 'filtering'],
    context: 'An S-Rank Hunter scans a dungeon rift containing 50 monsters to find S-Rank beasts.',
    prompt: 'How would you search the monster list and filter out non-S-rank creatures?',
    objectives: ['Filter dungeon monsters', 'Identify S-Rank beasts', 'Map to search/filtering'],
    sampleReasoning: 'bosses = [m for m in dungeon_monsters if m.rank == "S"] filters the beasts.',
    effectivenessScore: 94,
    theme: 'anime',
    caseStudyId: 'cs-anime-pokedex',
    themeStep: 2,
    themeEmoji: '🐉'
  },
  {
    title: 'Chakra Exhaustion Substitution Guard',
    difficulty: 'Builder',
    concepts: ['error handling', 'try except'],
    context: 'During battle, a shinobi\'s chakra drops below critical level while casting a jutsu.',
    prompt: 'How would you catch this low-chakra exception to automatically trigger a wood clone substitution?',
    objectives: ['Detect low chakra', 'Catch exception', 'Map to try/except'],
    sampleReasoning: 'try: cast_jutsu() except ChakraExhausted: trigger_substitution() handles exhaustion.',
    effectivenessScore: 97,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 9,
    themeEmoji: '⚔️'
  },
  {
    title: 'Shinobi Guild Power Ranker',
    difficulty: 'Builder',
    concepts: ['algorithms', 'sorting'],
    context: 'The Hokage needs to rank 20 shinobi by combat power level from highest to lowest.',
    prompt: 'How would you order the list of shinobi scores from highest to lowest?',
    objectives: ['Order combat scores', 'Sort list descending', 'Map to sorting algorithms'],
    sampleReasoning: 'ninja_list.sort(key=lambda n: n.power, reverse=True) ranks the shinobi.',
    effectivenessScore: 96,
    theme: 'anime',
    caseStudyId: 'cs-anime-pokedex',
    themeStep: 3,
    themeEmoji: '🐉'
  },
  {
    title: 'Forbidden Leaf Scroll Archive Saver',
    difficulty: 'Builder',
    concepts: ['files', 'file io'],
    context: 'The Hokage wants to record secret ninjutsu scroll instructions into a permanent file archive.',
    prompt: 'How would you write jutsu scroll instructions into a file for permanent archival?',
    objectives: ['Open file for writing', 'Write scroll text', 'Map to file I/O'],
    sampleReasoning: 'with open("scrolls.txt", "w") as f: f.write(scroll_text) archives the jutsu permanently.',
    effectivenessScore: 95,
    theme: 'anime',
    caseStudyId: 'cs-anime-ninja',
    themeStep: 10,
    themeEmoji: '⚔️'
  }
];

async function run() {
  await resetData(scenarios);
  console.log(`Seeded ${scenarios.length} PyBe scenarios`);
  console.log(`  - Classic scenarios: ${scenarios.filter(s => s.theme === 'classic').length}`);
  console.log(`  - Chai Stall theme: ${scenarios.filter(s => s.theme === 'chai-stall').length}`);
  console.log(`  - ISRO theme: ${scenarios.filter(s => s.theme === 'isro').length}`);
  console.log(`  - Instagram theme: ${scenarios.filter(s => s.theme === 'instagram').length}`);
  console.log(`  - Food Delivery theme: ${scenarios.filter(s => s.theme === 'food-delivery').length}`);
  console.log(`  - AI Playlist theme: ${scenarios.filter(s => s.theme === 'ai-playlist').length}`);
  console.log(`  - Kota theme: ${scenarios.filter(s => s.theme === 'kota').length}`);
  console.log(`  - Potterheads theme: ${scenarios.filter(s => s.theme === 'potterheads').length}`);
  console.log(`  - Marvel theme: ${scenarios.filter(s => s.theme === 'marvel').length}`);
  console.log(`  - Anime theme: ${scenarios.filter(s => s.theme === 'anime').length}`);
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
