import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const chapters=['Story','Problem','Think','Solution','Threads','Python','Start','Join','GIL','Challenge','Mastered'];
const orders=['🍕 Pizza','🍔 Burger','🍜 Noodles','🥤 Drink'];

function Code({children}){return <pre className="code"><code>{children}</code></pre>}
function Feedback({ok,children}){return <div className={ok?'feedback ok':'feedback retry'}>{ok?'✓ ':'↺ '}{children}</div>}
function Choice({icon,label,active,onClick}){return <button className={active?'choice active':'choice'} onClick={onClick}><span>{icon}</span>{label}</button>}

function App(){
 const [step,setStep]=useState(0),[answers,setAnswers]=useState({}),[run,setRun]=useState(0),[reflection,setReflection]=useState('');
 const next=()=>setStep(s=>Math.min(s+1,chapters.length-1)); const back=()=>setStep(s=>Math.max(s-1,0));
 const setA=(k,v)=>setAnswers(a=>({...a,[k]:v}));
 return <main className="app">
  <header className="top"><div className="brand"><b>PyBe</b><small>Scenario-first Python</small></div><div className="title"><small>Learning Journey</small><b>🍽️ The Busy Restaurant · Multithreading</b></div><b className="pct">{Math.round(step/(chapters.length-1)*100)}%</b></header>
  <div className="bar"><i style={{width:`${step/(chapters.length-1)*100}%`}}/></div>
  <nav className="steps">{chapters.map((x,i)=><button key={x} className={i===step?'on':i<step?'done':''} onClick={()=>i<=step&&setStep(i)}><span>{i<step?'✓':i+1}</span><small>{x}</small></button>)}</nav>
  <section className="stage">
   {step===0&&<Story next={next}/>}{step===1&&<Problem next={next}/>}{step===2&&<Think a={answers.think} setA={v=>setA('think',v)} next={next}/>}{step===3&&<Solution next={next}/>}
   {step===4&&<Threads next={next}/>}{step===5&&<Python next={next}/>}{step===6&&<Start run={run} setRun={setRun} next={next}/>}{step===7&&<Join next={next}/>}{step===8&&<GIL next={next}/>}{step===9&&<Challenge a={answers.challenge} setA={v=>setA('challenge',v)} next={next}/>}{step===10&&<Mastered reflection={reflection} setReflection={setReflection}/>} 
  </section>
  <footer><button onClick={back} disabled={!step}>← Back</button><span>Chapter {step+1} of {chapters.length}</span><button onClick={next} disabled={step===chapters.length-1}>Next →</button></footer>
 </main>
}

function Story({next}){return <div className="scene center"><div className="restaurantIcon">🍽️</div><p className="eyebrow">A reasoning-first Python story</p><h1>One restaurant.<br/><em>Many orders.</em></h1><p className="lead">It is Friday night. The restaurant is full. Orders keep arriving.</p><div className="storyCards"><div>👨‍🍳<b>Ravi</b><small>one cook</small></div><div>🧾<b>Orders</b><small>arriving fast</small></div><div>⏳<b>Customers</b><small>waiting</small></div></div><div className="prompt"><b>Think before you code</b><span>Can one worker handle many jobs efficiently?</span></div><button className="primary" onClick={next}>Enter the restaurant →</button><small className="muted">No Python syntax yet. First, experience the problem.</small></div>}

function Problem({next}){return <div className="scene split"><div className="visual kitchen"><div className="tag">FRIDAY NIGHT · 8:00 PM</div><div className="counter">🧾 🧾 🧾 🧾</div><div className="chef single">👨‍🍳</div><div className="pan">🍳</div><div className="queue">👩‍🦰　👨‍🦱　👩　👨　👵</div></div><div className="copy"><p className="eyebrow">Observe the problem</p><h2>The orders arrive one after another.</h2><p>Ravi cooks pizza. Then burger. Then noodles. Each job waits for the previous job to finish.</p><div className="timeline"><span>🍕</span><i/><span>🍔</span><i/><span>🍜</span></div><p className="muted">The restaurant is not necessarily doing more work. It is waiting on one worker.</p><button className="primary" onClick={next}>Ask the team →</button></div></div>}

function Think({a,setA,next}){let ok=a==='workers';return <div className="scene split"><div className="copy"><p className="eyebrow">Think like a problem solver</p><h2>How could the restaurant handle several jobs?</h2><p>We have the same orders. The problem is how the work is organized.</p><div className="choices"><Choice icon="👨‍🍳" label="Make one cook work even harder" active={a==='harder'} onClick={()=>setA('harder')}/><Choice icon="👥" label="Let several workers handle separate jobs" active={a==='workers'} onClick={()=>setA('workers')}/><Choice icon="🗑️" label="Ignore some orders" active={a==='ignore'} onClick={()=>setA('ignore')}/></div>{a&&<Feedback ok={ok}>{ok?'Exactly. Several workers can make progress on different tasks while other tasks are waiting.':'That does not solve the organization problem. Think about doing more than one task at the same time.'}</Feedback>}<button className="primary" disabled={!ok} onClick={next}>See the idea →</button></div><div className="visual thought"><div className="bigChef">👨‍🍳</div><div className="question">“What if each worker handled a different order?”</div></div></div>}

function Solution({next}){return <div className="scene center"><p className="eyebrow">The restaurant changes its workflow</p><h2>One worker becomes a small team.</h2><div className="team"><div className="worker w1">👨‍🍳<b>Pizza</b><small>Thread 1</small></div><div className="worker w2">👩‍🍳<b>Burger</b><small>Thread 2</small></div><div className="worker w3">🧑‍🍳<b>Noodles</b><small>Thread 3</small></div></div><div className="flow"><span>Orders</span><b>→</b><span className="chip">separate tasks</span><b>→</b><span>workers make progress</span></div><div className="takeaway">This is the intuition behind <strong>multithreading</strong>: multiple threads can make progress within one program, especially when tasks spend time waiting for input/output.</div><button className="primary" onClick={next}>Name the workers →</button></div>}

function Threads({next}){return <div className="scene pad"><div className="heading"><p className="eyebrow">Story → abstraction</p><h2>Meet the threads.</h2><p>Each thread is like a worker following its own sequence of instructions.</p></div><div className="threadMap"><div className="program">🧠<b>One Python process</b><small>the restaurant</small></div><div className="arrow">↙　↓　↘</div><div className="threadCards"><div>🧵 <b>Thread 1</b><small>cook pizza</small></div><div>🧵 <b>Thread 2</b><small>cook burger</small></div><div>🧵 <b>Thread 3</b><small>serve drink</small></div></div></div><div className="takeaway">A thread is a separate path of execution inside a process. Threads share the process's memory, so shared data must be handled carefully.</div><button className="primary" onClick={next}>Now translate the story to Python →</button></div>}

function Python({next}){return <div className="scene split"><div className="copy"><p className="eyebrow">Story → Python</p><h2>The worker becomes a thread.</h2><p>Python's <code>threading</code> module gives us the tools to create and start threads.</p><Code>{`import threading\n\ndef cook(order):\n    print("Cooking", order)\n\nt1 = threading.Thread(target=cook, args=("Pizza",))\nt2 = threading.Thread(target=cook, args=("Burger",))`}</Code><div className="mapping"><span>👨‍🍳 Worker</span><b>→</b><code>Thread</code><span>🍕 Order</span><b>→</b><code>argument</code></div><button className="primary" onClick={next}>What does start() do? →</button></div><div className="visual codeVisual"><div className="terminalTitle">restaurant.py</div><div className="terminalLine"><i/> t1 = Thread(...)</div><div className="terminalLine"><i/> t2 = Thread(...)</div><div className="miniWorkers"><span>🧵</span><span>🧵</span></div></div></div>}

function Start({run,setRun,next}){return <div className="scene pad"><div className="heading"><p className="eyebrow">Animation: start()</p><h2>Creating a thread is not the same as starting it.</h2><p>Press the button. Watch the jobs leave the kitchen together.</p></div><button className="runBtn" onClick={()=>setRun(r=>r+1)}>▶ Start Threads</button><div className={'race '+(run?'running':'')} key={run}><div><b>Thread 1</b><span>🧵 🍕</span></div><div><b>Thread 2</b><span>🧵 🍔</span></div><div><b>Thread 3</b><span>🧵 🥤</span></div></div><Code>{`t1.start()\nt2.start()\nt3.start()`}</Code><div className="takeaway"><strong>start()</strong> asks Python to begin executing the target function in that thread. The exact order in which threads run is not something your program should casually assume.</div><button className="primary" onClick={next}>Wait for the team →</button></div>}

function Join({next}){return <div className="scene split"><div className="visual joinVisual"><div className="plates">🍕　🍔　🥤</div><div className="workersJoin"><span>🧵</span><span>🧵</span><span>🧵</span></div><div className="table">🍽️</div></div><div className="copy"><p className="eyebrow">Animation: join()</p><h2>The manager waits for everyone.</h2><p>Sometimes the main program needs to wait until a thread finishes before moving on.</p><Code>{`t1.start()\nt2.start()\n\nt1.join()\nt2.join()\n\nprint("All orders finished")`}</Code><div className="takeaway"><strong>join()</strong> blocks the calling thread until the selected thread completes.</div><button className="primary" onClick={next}>One important catch →</button></div></div>}

function GIL({next}){return <div className="scene pad"><div className="heading"><p className="eyebrow">Don't oversimplify the story</p><h2>Three cooks do not always mean three CPU cores.</h2><p>Python implementations have important details. In CPython, the Global Interpreter Lock (GIL) limits execution of Python bytecode to one thread at a time.</p></div><div className="gilScene"><div className="cpu">🧠<b>CPython</b><small>one GIL gate</small></div><div className="gate">🔒 GIL</div><div className="cpuThreads"><span>🧵 Thread A</span><span>🧵 Thread B</span><span>🧵 Thread C</span></div></div><div className="compareBox"><div><b>Good fit</b><p>I/O-bound work: network, files, waiting for responses. Threads can make progress while another thread waits.</p></div><div><b>Not a magic speed button</b><p>CPU-bound Python bytecode often does not become faster just by adding threads in CPython. Multiprocessing or other approaches may be more suitable.</p></div></div><button className="primary" onClick={next}>Test your understanding →</button></div>}

function Challenge({a,setA,next}){let ok=a==='io';return <div className="scene pad"><div className="heading"><p className="eyebrow">Transfer challenge</p><h2>Where would threads make the most sense?</h2><p>A Python program must download 20 web pages. Each download spends time waiting for the network.</p></div><div className="choices wideChoices"><Choice icon="🌐" label="Use threads for the waiting downloads" active={a==='io'} onClick={()=>setA('io')}/><Choice icon="🧮" label="Assume threads automatically make CPU-heavy calculations faster" active={a==='cpu'} onClick={()=>setA('cpu')}/><Choice icon="⏸️" label="Run everything strictly one after another" active={a==='serial'} onClick={()=>setA('serial')}/></div>{a&&<Feedback ok={ok}>{ok?'Good reasoning. Network I/O spends time waiting, so threads can overlap that waiting and keep the program productive.':'That conclusion is too broad. In CPython, threads are especially useful for I/O-bound work; CPU-bound Python code has the GIL consideration.'}</Feedback>}<Code>{`import threading\n\ndef download(url):\n    # network I/O\n    ...\n\nthreads = []\nfor url in urls:\n    t = threading.Thread(target=download, args=(url,))\n    t.start()\n    threads.append(t)\n\nfor t in threads:\n    t.join()`}</Code><button className="primary" disabled={!ok} onClick={next}>Finish the story →</button></div>}

function Mastered({reflection,setReflection}){return <div className="scene pad center"><div className="badge">✓ Concept mastered</div><h1>You can now <em>see</em> multithreading.</h1><div className="conceptCore"><b>MULTITHREADING</b><small>one process · multiple threads · shared memory</small></div><div className="concepts"><div>🧵<b>Thread</b><small>path of execution</small></div><div>▶️<b>start()</b><small>begin the thread</small></div><div>⏳<b>join()</b><small>wait for completion</small></div><div>🔒<b>GIL</b><small>CPython detail</small></div></div><label className="reflection"><b>Explain multithreading in your own words.</b><textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="Multithreading means..."/><small>Try to mention threads, one process, and why I/O-bound work can benefit.</small></label><div className="formula">🍽️ ONE RESTAURANT <b>→</b> 🧵 MANY WORKERS <b>→</b> MULTIPLE TASKS MAKE PROGRESS</div></div>}

createRoot(document.getElementById('root')).render(<App/>);
